# Generated by Django 5.2 on 2025-04-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField()),
                ('name', models.CharField(choices=[('SE', 'Soul Edge'), ('SB', 'Soul Blade'), ('SC', 'Soulcalibur'), ('SCII', 'Soulcalibur II'), ('SCIII', 'Soulcalibur III'), ('SCL', 'Soulcalibur Legends'), ('SCIV', 'Soulcalibur IV'), ('SCBD', 'Soulcalibur: Broken Destiny'), ('SCV', 'Soulcalibur V'), ('SCVI', 'Soulcalibur VI')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('OST', 'Original Soundtrack'), ('GR', 'Gamerip')], max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Music.game')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(max_length=10)),
                ('variation_type', models.CharField(choices=[('ORI', 'Original'), ('ARR', 'Arranged'), ('EXT', 'Extended'), ('SHORT', 'Shortened'), ('FRAG', 'Fragment')], default='ORI', max_length=6)),
                ('albums', models.ManyToManyField(related_name='songs', to='Music.album')),
                ('original_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='Music.song')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.character')),
                ('game_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.gamemode')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='Music.song')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.stage')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='stages',
            field=models.ManyToManyField(related_name='characters', to='Music.stage'),
        ),
    ]
