# Generated by Django 5.2 on 2025-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('OST', 'Original Soundtrack'), ('GR', 'Gamerip')], default='OST', max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(choices=[('SE', 'Soul Edge'), ('SB', 'Soul Blade'), ('SC', 'Soulcalibur'), ('SCII', 'Soulcalibur II'), ('SCIII', 'Soulcalibur III'), ('SCL', 'Soulcalibur Legends'), ('SCIV', 'Soulcalibur IV'), ('SCBD', 'Soulcalibur: Broken Destiny'), ('SCV', 'Soulcalibur V'), ('SCVI', 'Soulcalibur VI')], max_length=50),
        ),
    ]
