# Generated by Django 5.2 on 2025-04-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_album_type_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_number',
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.song')),
            ],
            options={
                'ordering': ['album', 'song_number'],
                'unique_together': {('album', 'song')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', through='Music.AlbumSong', to='Music.song'),
        ),
    ]
